[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["cd floally-mvp/backend && pip install -r requirements.txt"]

[start]
cmd = "cd floally-mvp/backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
