[build]
builder = "NIXPACKS"
buildCommand = "pip install -r floally-mvp/backend/requirements.txt"

[deploy]
startCommand = "cd floally-mvp/backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
